### ISSUE TITLE
Неверная длина ключа

### ISSUE THREAD

**Issue by lesnka** [eagleas/webmoney#18]
Использую вебкипер классик, получила файл ключей, расшифровала его. Получилась длина 229 символов. У вас валидация на 220 символов. Подаю ключ в виде Base64. В чем может быть проблема?

**Comment by scarfacedeb** [comment]
та же самая проблема.
@lesnka не подскажите как вы ее решили?

**Comment by lesnka** [comment]
Подскажу. Попробуйте преобразовывать файл из командной строки используя (key.kwm замените на Ваш файл)
code64 -K64 key.kwm

**Comment by scarfacedeb** [comment]
Спасибо большое! А то здесь черт ногу сломит разобраться.

**Comment by eagleas** [comment]
@scarfacedeb Спасибо за отзыв, коллега! Пулл-реквесты на документацию принимаются.

**Comment by scarfacedeb** [comment]
К сожалению, я очень плохо знаком с webmoney, и текущая задача только косвенно с этим связана.
Поэтому внятно объяснить непонятные части вряд ли получится.)
