### ISSUE TITLE
How to get the key?

### ISSUE THREAD

**Issue by phuongnd08** [eagleas/webmoney#19]
From the kwm file, how do I get the key value to use with this:
```
class MyWM
  include Webmoney
end
@wm = MyWM.new(:wmid => '123456789012', :password => 'my_pass', :key => 'gQABAIR6...2cC8FZTyKyjBM=')
```

Thanks for help (I use Key Extractor but it gives me 2 value: Modulus and D)

**Comment by eagleas** [comment]
Hello.
You should to use 'base64' utitity from original wmsigner tool: https://github.com/eagleas/wmsigner
More information about wmsigner here: http://wiki.wmtransfer.com/projects/webmoney/wiki/WMSigner

**Comment by phuongnd08** [comment]
I notice you changed the params of Webmoney#initialize a bit.
I'm using it like this:
```ruby
@wm = MyWM.new(
      :wmid => 'MyId',
      :password => 'mypassword',
      :key => "/path/to/my.kwm"
    )
```
but getting
``` 
OpenSSL::PKey::RSAError:
       Neither PUB key nor PRIV key: nested asn1 error
```

**Comment by eagleas** [comment]
> :key => "/path/to/my.kwm"
It's incorrect.
